# Generated by Django 3.2.18 on 2023-04-10 11:51

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_alter_booking_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 10, 11, 52, 14, 932353, tzinfo=utc), message='Please choose a date and time in the future.')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Please enter a value between 1-8'), django.core.validators.MaxValueValidator(8, message='Please enter a value between 1-8')]),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date_time', 'email')},
        ),
    ]
