# Generated by Django 3.2.18 on 2023-04-10 11:55

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_alter_booking_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 10, 11, 56, 28, 638927, tzinfo=utc), message='Please choose a date and time in the future.')]),
        ),
    ]
